version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my-research-digest-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend-node
      - backend-python
    command: "/bin/sh -c 'while :; do sleep 6h & wait $!; nginx -s reload; done & nginx -g \"daemon off;\"'" # Keep Nginx running and reload for certs
    networks:
      - my-research-digest-network

  # certbot:
  #   image: certbot/certbot
  #   container_name: my-research-digest-certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - nginx
  #   command: "certbot certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com --agree-tos --no-eff-email -d my-research-digest.com -d www.my-research-digest.com"
  #   networks:
  #     - my-research-digest-network

  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: my-research-digest-backend-node
    env_file:
      - ./backend-node/prod.env
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - my-research-digest-network

  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: my-research-digest-backend-python
    env_file:
      - ./backend-python/prod.env
    networks:
      - my-research-digest-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_AUTH0_REDIRECT_URI=${VITE_AUTH0_REDIRECT_URI}
        - VITE_MONGO_API_URL=${VITE_MONGO_API_URL}
        - VITE_ADMIN_EMAILS=${VITE_ADMIN_EMAILS}
    container_name: my-research-digest-frontend
    depends_on:
      - backend-node # Frontend needs backend for API calls
    networks:
      - my-research-digest-network

  mongodb:
    image: mongo:latest
    container_name: my-research-digest-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - my-research-digest-network

volumes:
  mongodb_data:

networks:
  my-research-digest-network:
    driver: bridge
