services:
  mongodb:
    image: mongo:latest
    container_name: my-research-digest-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - my-research-digest-network

volumes:
  mongodb_data:

networks:
  my-research-digest-network:
    driver: bridge 