export function TermsOfService() {
  return (
    <div className="max-w-6xl mx-auto px-6 py-20">
      <h1 className="text-3xl font-bold mb-4">Terms of Service</h1>
      <p>Last updated: November 19, 2025</p>

      <p className="mt-4">
        Please read these Terms of Service ("Terms") carefully before using the My Research Digest website (the "Service") operated by us. Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
      </p>
      
      <p className="mt-4">
        By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">1. Description of Service</h2>
      <p>
        My Research Digest is a free, open-source tool designed to help researchers track scientific literature. The Service provides weekly, AI-assisted digests of relevant academic papers based on user-defined keywords and research interests. The Service sources information from publicly available, third-party scientific databases such as arXiv, Semantic Scholar, and PubMed.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">2. Accounts</h2>
      <p>
        When you create an account, you must provide accurate and complete information. You are responsible for safeguarding your password and for all activities under your account. You must notify us immediately of any unauthorized use of your account.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">3. AI-Generated Content</h2>
      <p>
        The Service uses artificial intelligence (AI) to generate summaries, key findings, and other synthesized content ("AI Content"). You acknowledge that:
      </p>
      <ul className="list-disc list-inside mt-4">
        <li>AI Content is generated by automated systems and may contain errors, inaccuracies, or omissions.</li>
        <li>AI Content is for informational purposes only and should not be considered a substitute for reading the original research papers.</li>
        <li>We are not responsible for any reliance you place on AI Content. You should always verify the information by consulting the source publications.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-4 mt-8">4. Use of Third-Party Sources</h2>
      <p>
        The Service retrieves data from third-party sources. We do not own or control these sources and are not responsible for their content, availability, or accuracy. Your use of these third-party sources is subject to their respective terms and conditions.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">5. Open Source</h2>
      <p>
        My Research Digest is an open-source project. The source code is made available under the MIT License. You are free to use, modify, and distribute the code in accordance with the license terms.
      </p>
      
      <h2 className="text-2xl font-bold mb-4 mt-8">6. User Conduct</h2>
      <p>
        You agree not to use the Service for any unlawful purpose or to engage in any activity that could harm the Service, its users, or its reputation.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">7. Disclaimer of Warranties</h2>
      <p>
        The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, regarding the operation or availability of the Service or the accuracy of the AI Content.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">8. Limitation of Liability</h2>
      <p>
        In no event shall we be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the Service or the AI Content.
      </p>
      
      <h2 className="text-2xl font-bold mb-4 mt-8">9. Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-8">10. Contact Us</h2>
      <p>If you have any questions about these Terms, please contact us by email at: contact@my-research-digest.com</p>
    </div>
  );
}
